#!/bin/bash

source ${PWD}/.localdev

localdev_gid=`id -g ${USER}`
localdev_uid=`id -u ${USER}`

if [ ! -f .localdev-image ]; then
    echo "Building image..."
    docker build -q \
        --build-arg localdev_group_id=${localdev_gid} \
        --build-arg localdev_user_id=${localdev_uid} \
        -t coba_runner \
        https://github.com/DockerLocalDev/${runner}-localdev.git \
        > .localdev-image

    if [ $? != 0 ]; then
        echo Failed building image
        exit 1
    fi
fi

image_id=`cat .localdev-image`

docker run -it --rm \
    -v ${PWD}:/home/localdev/workspace \
    "${image_id}" "$@"
