#!/bin/bash

localdev_gid=`id -g ${USER}`
localdev_uid=`id -u ${USER}`

echo "Building image of $1..."
docker build -q \
    --build-arg localdev_group_id=${localdev_gid} \
    --build-arg localdev_user_id=${localdev_uid} \
    https://github.com/DockerLocalDev/$1-localdev.git \
    > ${PWD}/.localdev/$1

if [ $? != 0 ]; then
    rm ${PWD}/.localdev/$1
    echo Failed building image $1
    exit 1
fi
