#!/bin/bash

function build_image {
    local localdev_gid=`id -g ${USER}`
    local localdev_uid=`id -u ${USER}`

    echo "Building image of $1..."
    docker build -q \
        --build-arg localdev_group_id=${localdev_gid} \
        --build-arg localdev_user_id=${localdev_uid} \
        https://github.com/DockerLocalDev/$1-localdev.git \
        > ${PWD}/.localdev/$1

    if [ $? != 0 ]; then
        echo Failed building image $1
        exit 1
    fi
}

function run {
    local image_id=`cat ${PWD}/.localdev/$1`
    echo "Run container for $1..."
    shift
    docker run -it --rm \
        -v ${PWD}:/home/localdev/workspace \
        "${image_id}" "$@"
}

mkdir -p ${PWD}/.localdev

if [ ! -f ${PWD}/.localdev/$1 ]; then
    build_image $1
fi

run "$@"
